# Melee weapon classes
# IDs 0 - 19
WEAPONM_SWORD = 0
WEAPONM_DAGGER = 1
WEAPONM_SPEAR = 2
WEAPONM_AXE = 3
WEAPONM_SHOVEL = 4
WEAPONM_CLUB = 5
WEAPONM_HAMMER = 6
WEAPONM_STAFF = 7
WEAPONM_MACE = 8
WEAPONM_FLAIL = 9

# Ranged weapon classes
# IDs 20 - 39
WEAPONR_JAVELIN = 20
WEAPONR_SLING = 21
WEAPONR_DART = 22
WEAPONR_BOW = 23
WEAPONR_STONE = 24

# Magic weapon classes
# IDs 40 - 59
WEAPONJ_WAND = 40
WEAPONJ_STAFF = 41
WEAPONJ_ORB = 42
